### ISSUE TITLE
Error: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by mirgee** [katyo/publish-crates#74]
Running the following, seemingly correct job (which mimicks [the usage example from the README](https://github.com/katyo/publish-crates#usage-examples))
```
jobs:
  publish-rust-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path wrappers/rust/Cargo.toml
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v1
        with:
          path: wrappers/rust
          dry-run: true
```
results in the following output
```
Searching cargo packages at 'wrappers/rust'
Found packages: wrapper-test
Checking packages consistency
Error: Cannot read property 'path' of undefined
```
This error is probably thrown downstream of [`checkPackages()`](https://github.com/katyo/publish-crates/blob/main/src/package.ts#L141), and is not a result of an issue with the published crate itself, as it can be successfully published locally. The same error is thrown when a crates.io token is used with `dry-run: false`.
