### ISSUE TITLE
Check-repo pass changed crate, strange behaviour

### ISSUE THREAD

**Issue by boozook** [katyo/publish-crates#743]
I don't understand why [that job](https://github.com/boozook/playdate/actions/runs/8965082458/job/24617906492#step:6:5) not failed.
It have to fail because package `playdate` updated, but its version hasn't been changed [there](https://github.com/boozook/playdate/pull/319/files#diff-d52242a6ff63ec064b12584f23e4b55824b91027b73e0b3ec2c0c01e817f9a2e).

Action configuration:
```yaml
katyo/publish-crates@v2:
  with:
    dry-run: true
    check-repo: true
    ignore-unpublished-changes: false
    registry-token: ***
    token: ***
    path: .
    publish-delay: 0
    no-verify: false
```

[There is workflow with action call.](https://github.com/boozook/playdate/blob/main/.github/workflows/publish.yml#L57-L66)
